run:
  timeout: 1m

linters:
  enable:
    - lll
    - gofmt
    - revive
    - exportloopref
    - unparam
    - gocritic
    - staticcheck
    - gosec
    - errcheck
    - prealloc
    - ineffassign

linters-settings:
  lll:
    line-length: 130
