name: tests
on: [push, pull_request]
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Set up Go 1.13
                uses: actions/setup-go@v1
                with:
                    go-version: 1.13
            - name: Check out code into the Go module directory
                uses: actions/checkout@v1
                with:
                    fetch-depth: 1
                    path: go/src/github.com/rafaelsq/wtc
            - name: GolangCI-Lint
                run: |
                    get -u github.com/golangci/golangci-lint/cmd/golangci-lint
                    golangci-lint run
                env:
                    GOPATH: /home/runner/work/rafaelsq/wtc
            - name: Test
                run: go test -race -cover ./...
                env:
                    GOPATH: /home/runner/work/rafaelsq/wtc
